version: '2'
services:
  bootstrap:
    build: monitored-geth-client
    restart: on-failure
    container_name: bootstrap
    hostname: bootstrap
    links:
      - netstats
    entrypoint: /root/start.sh
    volumes:
      - ./flowlabs-chain/node_bootstrap:/root/.ethereum/devchain:rw
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./timezone:/etc/localtime:ro
    command: '--datadir=~/.ethereum/devchain \
              --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322 \
              --rpcapi "admin,db,personal,eth,net,web3,miner,debug" \
              --rpccorsdomain="*" \
              --networkid=281096 \
              --rpc \
              --rpcaddr="0.0.0.0"'
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"

  eth1:
    build: monitored-geth-client
    restart: on-failure
    container_name: eth1
    links:
      - bootstrap
      - netstats
    entrypoint: /root/start.sh
    volumes:
      - ./flowlabs-chain/node_1:/root/.ethereum/devchain:rw
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./timezone:/etc/localtime:ro
    command: '--datadir=~/.ethereum/devchain \
              --mine \
              --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@XXX:30303" \
              --rpcapi "admin,db,personal,eth,net,web3,miner,debug"
              --rpccorsdomain="*" \
              --networkid=281096 \
              --rpc \
              --rpcaddr="0.0.0.0"'
    ports:
      - "8648:8545"

  eth2:
    build: monitored-geth-client
    restart: on-failure
    container_name: eth2
    links:
      - bootstrap
      - netstats
    entrypoint: /root/start.sh
    volumes:
      - ./flowlabs-chain/node_2:/root/.ethereum/devchain:rw
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./timezone:/etc/localtime:ro
    command: '--datadir=~/.ethereum/devchain \
              --mine \
              --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@XXX:30303" \
              --rpcapi "admin,db,personal,eth,net,web3,miner,debug"
              --rpccorsdomain="*" \
              --networkid=281096 \
              --rpc \
              --rpcaddr="0.0.0.0"'
    ports:
      - "8649:8545"

  netstats:
    build: eth-netstats
    restart: on-failure
    container_name: netstats
    environment:
      - WS_SECRET=eth-net-stats-secret
    volumes:
      - ./timezone:/etc/localtime:ro
    ports:
      - "4000:3000"
